version: '3'
services:

  app:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - "logsvolume:/usr/src/app/logs"
    restart: "on-failure"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DBPORT=${DBPORT}
      - mongoDBHostname=${mongoDBHostname}
    networks:
      - ass

  mongo:
    image: "mongo"
    command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
    environment:
      MONGO_INITDB_DATABASE: ACME_Explorer
    volumes:
      - "logsvolume:/var/log/mongodb"
      - "datavolume:/data/db"
    expose:
      - "${DBPORT}"
    networks:
      - ass

networks:
  ass:
    driver: bridge

volumes:
  datavolume:
  logsvolume:
    external: false
